name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Run tests with increased timeout and retry
      run: |
        retries=3
        count=0
        until [ $count -ge $retries ]
        do
          dotnet test --no-build --verbosity normal --timeout 600000 && break
          count=$((count+1))
          echo "Test run $count failed. Retrying in 10 seconds..."
          sleep 10
        done
      continue-on-error: false
